fos_rest:
  routing_loader:
    default_format: json

  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }

  view:
    view_response_listener: true

